### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Epistol** [jsrn/howoldisit#225] opened 2019-03-14 13:50 UTC
504 gateway :/

**Comment by alexlobanov** [comment] 2019-04-04 05:59
@jsrn I think it's good idea to have some monitoring solution, like ApiChecker.com - if you don't have yet. And with status page - your site users @Epistol and myself will be in loop as well.

**Comment by jsrn** [comment] 2019-04-04 08:24
Thanks for flagging this. I think a big part of the issue is that I'm serving a whole node app for a static page with some JS.

Soon I will try to do a static build, and then we should be able to deploy that with hopefully no further problems.

**Comment by jsrn** [comment] 2019-04-07 18:26
It's alive! Thanks again.

**Closed by jsrn** 2019-04-07 18:26 UTC
